# Generated by Django 4.0.3 on 2022-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2022)),
                ('model', models.CharField(max_length=150, verbose_name='Model')),
                ('trim', models.CharField(help_text='Trim level', max_length=150, verbose_name='Trim')),
            ],
        ),
    ]
