# Generated by Django 4.0.3 on 2022-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_carmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='trim',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=150),
        ),
    ]
